sudo: false
language: node_js
node_js:
  - '10'
  - '12'
services:
  - mysql
before_install:
  - npm i npminstall -g
  - 'wget https://archive.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz'
  - 'tar xf zookeeper-3.4.6.tar.gz'
  - 'mv zookeeper-3.4.6/conf/zoo_sample.cfg zookeeper-3.4.6/conf/zoo.cfg'
  - './zookeeper-3.4.6/bin/zkServer.sh start'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `egg-sequelize-example-unittest`;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `egg-sequelize-ts-unittest`;'
install:
  - npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
