sudo: false
language: node_js
node_js:
  - '6'
  - '7'
  - '8'
services:
  - postgresql
install:
  - npm i npminstall && npminstall
before_script:
  - psql -c 'create database "example-unittest";' -U postgres
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
